spring.datasource.url=
spring.datasource.username=
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/lepay
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      filters: stat



